name: Deploy Static Site via SSH (Client-generated key)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  RSYNC_SRC: "."               # đổi thành "dist" nếu có build
  REMOTE_USER: "deploy"
  REMOTE_HOST: ${{ secrets.SERVER_IP }}
  REMOTE_PORT: ${{ secrets.SERVER_SSH_PORT }}
  REMOTE_PATH: "/var/www//test-deploy"
  SSH_KEY_PATH: "~/.ssh/deploy_key"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > $SSH_KEY_PATH
          chmod 600 $SSH_KEY_PATH
          ssh-keyscan -p "$REMOTE_PORT" -H "$REMOTE_HOST" >> ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: |
          ssh -i $SSH_KEY_PATH -p "$REMOTE_PORT" "$REMOTE_USER@$REMOTE_HOST" "mkdir -p '$REMOTE_PATH'"

      - name: Rsync files to server
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            -e "ssh -i $SSH_KEY_PATH -p $REMOTE_PORT" \
            "$RSYNC_SRC"/ "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"/
